{% set name = "typescript-eslint-eslint-plugin" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/typescript-eslint/typescript-eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3ec0ab265284798a09bdb9f083c9889c091e6451ede1bb728680c9cf3b06348d

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - nodejs
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
    - yarn
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/@typescript-eslint/eslint-plugin  # [unix]
    - if not exist %LIBRARY_INC%\\lib\\node_modules\\@typescript-eslint\\eslint-plugin 1            # [win]

about:
  home: https://github.com/typescript-eslint/typescript-eslint
  license: MIT
  license_file:
    - LICENSE
    - packages/eslint-plugin/ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
